services:
  - type: web
    name: organization-participation-backend
    runtime: node
    plan: free
    buildCommand: cd backend && pnpm install && pnpm run build
    startCommand: cd backend && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: RENDER_URL
        value: https://project-manage-organization-participation.onrender.com
    healthCheckPath: /health
    autoDeploy: true
