import {
  User,
  Organization,
  Participant,
  Event,
  Member,
  ActivityLog,
  AttendanceRecord,
  AttendanceStats,
  OrganizationRules,
} from '../types';

export function generateId(): string {
  return Math.random().toString(36).substr(2, 9);
}

export function loadInitialData() {
  // 사용자 데이터
  const users: User[] = [
    {
      id: 'user_1',
      name: '김관리자',
      email: 'admin@example.com',
      role: 'admin',
      createdAt: new Date('2023-01-01'),
      updatedAt: new Date('2023-01-01'),
    },
    {
      id: 'user_2',
      name: '이회원',
      email: 'member1@example.com',
      role: 'member',
      createdAt: new Date('2023-02-01'),
      updatedAt: new Date('2023-02-01'),
    },
    {
      id: 'user_3',
      name: '박회원',
      email: 'member2@example.com',
      role: 'member',
      createdAt: new Date('2023-02-15'),
      updatedAt: new Date('2023-02-15'),
    },
    {
      id: 'user_4',
      name: '최회원',
      email: 'member3@example.com',
      role: 'member',
      createdAt: new Date('2023-03-01'),
      updatedAt: new Date('2023-03-01'),
    },
    {
      id: 'user_5',
      name: '정회원',
      email: 'member4@example.com',
      role: 'member',
      createdAt: new Date('2023-03-15'),
      updatedAt: new Date('2023-03-15'),
    },
  ];

  // 조직 데이터
  const organizations: Organization[] = [
    {
      id: 'org_1',
      name: '독서모임 북클럽',
      description: '매주 모여서 책을 읽고 토론하는 독서모임입니다.',
      location: '서울 강남구',
      type: 'study',
      maxMembers: 20,
      currentMembers: 8,
      settings: {
        participationRule: '2', // 월 2회 이상
      },
      createdBy: 'user_1',
      createdAt: new Date('2023-01-01'),
      updatedAt: new Date('2023-01-01'),
    },
    {
      id: 'org_2',
      name: '등산동호회',
      description: '주말마다 산을 오르며 건강을 챙기는 등산동호회입니다.',
      location: '서울 전역',
      type: 'sports',
      maxMembers: 30,
      currentMembers: 12,
      settings: {
        participationRule: '1', // 월 1회 이상
      },
      createdBy: 'user_1',
      createdAt: new Date('2023-02-01'),
      updatedAt: new Date('2023-02-01'),
    },
    {
      id: 'org_3',
      name: '프로그래밍 스터디',
      description: 'JavaScript와 React를 함께 공부하는 스터디 그룹입니다.',
      location: '온라인',
      type: 'study',
      maxMembers: 15,
      currentMembers: 6,
      settings: {
        participationRule: '3', // 월 3회 이상
      },
      createdBy: 'user_2',
      createdAt: new Date('2023-03-01'),
      updatedAt: new Date('2023-03-01'),
    },
    {
      id: 'org_4',
      name: '요리모임',
      description: '다양한 요리를 함께 만들어 먹는 요리모임입니다.',
      location: '서울 마포구',
      type: 'social',
      maxMembers: 10,
      currentMembers: 5,
      settings: {
        participationRule: '제한없음',
      },
      createdBy: 'user_3',
      createdAt: new Date('2023-04-01'),
      updatedAt: new Date('2023-04-01'),
    },
  ];

  // 구성원 데이터
  const members: Member[] = [
    // 독서모임 구성원
    {
      id: 'member_1',
      name: '김독서',
      gender: 'male',
      birthYear: 1990,
      district: '강남구',
      organizationId: 'org_1',
      status: 'active',
      joinedAt: new Date('2023-01-15'),
      updatedAt: new Date('2023-01-15'),
    },
    {
      id: 'member_2',
      name: '이책사랑',
      gender: 'female',
      birthYear: 1985,
      district: '서초구',
      organizationId: 'org_1',
      status: 'active',
      joinedAt: new Date('2023-02-01'),
      updatedAt: new Date('2023-02-01'),
    },
    {
      id: 'member_3',
      name: '박문학',
      gender: 'male',
      birthYear: 1992,
      district: '송파구',
      organizationId: 'org_1',
      status: 'active',
      joinedAt: new Date('2023-02-15'),
      updatedAt: new Date('2023-02-15'),
    },
    // 등산동호회 구성원
    {
      id: 'member_4',
      name: '최산악',
      gender: 'male',
      birthYear: 1988,
      district: '노원구',
      organizationId: 'org_2',
      status: 'active',
      joinedAt: new Date('2023-02-10'),
      updatedAt: new Date('2023-02-10'),
    },
    {
      id: 'member_5',
      name: '정등반',
      gender: 'female',
      birthYear: 1995,
      district: '강북구',
      organizationId: 'org_2',
      status: 'active',
      joinedAt: new Date('2023-03-01'),
      updatedAt: new Date('2023-03-01'),
    },
    // 프로그래밍 스터디 구성원
    {
      id: 'member_6',
      name: '김코딩',
      gender: 'male',
      birthYear: 1993,
      district: '마포구',
      organizationId: 'org_3',
      status: 'active',
      joinedAt: new Date('2023-03-15'),
      updatedAt: new Date('2023-03-15'),
    },
  ];

  // 참여자 데이터 (기존 호환성을 위해 유지)
  const participants: Participant[] = [
    {
      id: 'participant_1',
      userId: 'user_2',
      organizationId: 'org_1',
      role: 'member',
      status: 'active',
      joinedAt: new Date('2023-01-15'),
      lastActiveAt: new Date('2023-12-01'),
      permissions: ['read', 'participate'],
      updatedAt: new Date('2023-01-15'),
    },
    {
      id: 'participant_2',
      userId: 'user_3',
      organizationId: 'org_1',
      role: 'member',
      status: 'active',
      joinedAt: new Date('2023-02-01'),
      lastActiveAt: new Date('2023-12-01'),
      permissions: ['read', 'participate'],
      updatedAt: new Date('2023-02-01'),
    },
    {
      id: 'participant_3',
      userId: 'user_4',
      organizationId: 'org_2',
      role: 'member',
      status: 'active',
      joinedAt: new Date('2023-02-15'),
      lastActiveAt: new Date('2023-11-25'),
      permissions: ['read', 'participate'],
      updatedAt: new Date('2023-02-15'),
    },
    {
      id: 'participant_4',
      userId: 'user_5',
      organizationId: 'org_2',
      role: 'member',
      status: 'active',
      joinedAt: new Date('2023-03-01'),
      lastActiveAt: new Date('2023-11-30'),
      permissions: ['read', 'participate'],
      updatedAt: new Date('2023-03-01'),
    },
    {
      id: 'participant_5',
      userId: 'user_2',
      organizationId: 'org_3',
      role: 'admin',
      status: 'active',
      joinedAt: new Date('2023-03-01'),
      lastActiveAt: new Date('2023-12-01'),
      permissions: ['read', 'write', 'admin'],
      updatedAt: new Date('2023-03-01'),
    },
    {
      id: 'participant_6',
      userId: 'user_3',
      organizationId: 'org_3',
      role: 'member',
      status: 'active',
      joinedAt: new Date('2023-03-15'),
      lastActiveAt: new Date('2023-11-28'),
      permissions: ['read', 'participate'],
      updatedAt: new Date('2023-03-15'),
    },
  ];

  // 이벤트 데이터
  const events: Event[] = [
    {
      id: 'event_1',
      organizationId: 'org_1',
      title: '11월 독서모임 - 미움받을 용기',
      description: '아들러 심리학에 대해 토론해보는 시간',
      date: new Date('2023-11-15'),
      location: '강남역 스타벅스',
      hostId: 'member_1',
      maxParticipants: 10,
      currentParticipants: 3,
      status: 'completed',
      attendees: ['member_1', 'member_2', 'member_3'],
      createdBy: 'user_1',
      createdAt: new Date('2023-11-01'),
      updatedAt: new Date('2023-11-15'),
    },
    {
      id: 'event_2',
      organizationId: 'org_2',
      title: '북한산 등반',
      description: '가을 단풍을 보며 북한산 백운대 등반',
      date: new Date('2023-11-20'),
      location: '북한산 국립공원',
      hostId: 'member_4',
      maxParticipants: 15,
      currentParticipants: 5,
      status: 'completed',
      attendees: ['member_4', 'member_5'],
      createdBy: 'user_2',
      createdAt: new Date('2023-11-10'),
      updatedAt: new Date('2023-11-20'),
    },
    {
      id: 'event_3',
      organizationId: 'org_3',
      title: 'React Hooks 스터디',
      description: 'useState, useEffect 심화 학습',
      date: new Date('2023-12-01'),
      location: '온라인 (Zoom)',
      hostId: 'member_6',
      maxParticipants: 8,
      currentParticipants: 3,
      status: 'published',
      attendees: ['member_6'],
      createdBy: 'user_2',
      createdAt: new Date('2023-11-25'),
      updatedAt: new Date('2023-11-25'),
    },
  ];

  // 활동 로그 데이터
  const activityLogs: ActivityLog[] = [
    {
      id: 'log_1',
      organizationId: 'org_1',
      userId: 'user_1',
      action: 'organization_created',
      details: '독서모임 북클럽이 생성되었습니다.',
      timestamp: new Date('2023-01-01'),
      metadata: { organizationName: '독서모임 북클럽' },
    },
    {
      id: 'log_2',
      organizationId: 'org_1',
      userId: 'user_2',
      action: 'member_joined',
      details: '이회원님이 조직에 가입했습니다.',
      timestamp: new Date('2023-01-15'),
      metadata: { memberName: '이회원' },
    },
    {
      id: 'log_3',
      organizationId: 'org_1',
      userId: 'user_1',
      action: 'event_created',
      details: '11월 독서모임 이벤트가 생성되었습니다.',
      timestamp: new Date('2023-11-01'),
      metadata: { eventTitle: '11월 독서모임 - 미움받을 용기' },
    },
    {
      id: 'log_4',
      organizationId: 'org_2',
      userId: 'user_1',
      action: 'organization_created',
      details: '등산동호회가 생성되었습니다.',
      timestamp: new Date('2023-02-01'),
      metadata: { organizationName: '등산동호회' },
    },
    {
      id: 'log_5',
      organizationId: 'org_2',
      userId: 'user_2',
      action: 'event_created',
      details: '북한산 등반 이벤트가 생성되었습니다.',
      timestamp: new Date('2023-11-10'),
      metadata: { eventTitle: '북한산 등반' },
    },
  ];

  return {
    user: users[0], // 현재 사용자는 첫 번째 사용자 (관리자)
    users,
    organizations,
    participants,
    members,
    events,
    activityLogs,
    attendanceRecords: [] as AttendanceRecord[],
    attendanceStats: [] as AttendanceStats[],
    organizationRules: [] as OrganizationRules[],
  };
}
